name: "foreverbull python action"
inputs:
  path:
    description: "Path to the file to test"
    required: true
  assets:
    description: "Assets to download"
    required: true
  start:
    description: "Start the server"
    required: true
  end:
    description: "End the server"
    required: true
  alpaca_key:
    description: "Alpaca API Key"
    required: true
  alpaca_secret:
    description: "Alpaca API Secret"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Run
      shell: bash
      run: |
        pip install https://github.com/lhjnilsson/foreverbull/releases/download/0.0.2403051754/foreverbull-0.0.2403051754-py3-none-any.whl
        foreverbull env start ${{ inputs.alpaca_key }} ${{ inputs.alpaca_secret }}
        foreverbull service zipline backtest lhjnilsson/zipline:0.0.2403051754
        foreverbull backtest create action_backtest ${{ inputs.start }} ${{ inputs.end }} ${{ inputs.assets }} --backtest-service zipline
        pytest ${{ inputs.path }} --backtest=action_backtest
    - name: Teardown
      shell: bash
      run: foreverbull env stop
